### ISSUE TITLE
Cannot do HTTPS uploads

### ISSUE THREAD

**Issue by jbg** [fmetzger/android-sensorium#23]
When I try to do an HTTPS upload, it immediately appears to complete with the message:

    Upload finished with:

(nothing follows the colon).

On the nginx server, I see:

    Apr 10 20:54:12 www nginx[232]: www nginx: 2017/04/10 20:54:12 [info] 232#232: *1 client closed connection while SSL handshaking, client: ::ffff:1.2.3.4, server: [::]:443

If an SSL handshake failure is happening, it would be good to show/log the reason. The server is a standard nginx TLS configuration. Please let me know if you want any additional information.

**Comment by aaaaalbert** [comment]
Thanks for your bug report, @jbg!

So you see the message [constructed here](https://github.com/fmetzger/android-sensorium/blob/91e55198a8bb23b20655be293027dc6002ead32c/Sensorium/src/at/univie/sensorium/extinterfaces/HTTPSUploader.java#L87-L88) (and [output here](https://github.com/fmetzger/android-sensorium/blob/91e55198a8bb23b20655be293027dc6002ead32c/Sensorium/src/at/univie/sensorium/extinterfaces/HTTPSUploader.java#L92)). None of the functional/exception-handling clauses in the [upload function](https://github.com/fmetzger/android-sensorium/blob/91e55198a8bb23b20655be293027dc6002ead32c/Sensorium/src/at/univie/sensorium/extinterfaces/HTTPSUploader.java#L101-L169) changed the result string.

Could you perhaps take a look at your device's debug log (`adb logcat` on the command line, or use Android Studio) and check if you see a [stack trace](https://github.com/fmetzger/android-sensorium/blob/91e55198a8bb23b20655be293027dc6002ead32c/Sensorium/src/at/univie/sensorium/extinterfaces/HTTPSUploader.java#L146-L160)? I'd like to know what's going on exactly before we start coding a fix.

------

Besides the triage, I totally agree with you:
>If an SSL handshake failure is happening, it would be good to show/log the reason.

The user should not be left unclear about the status of the upload process, even if the app currently lacks means to work around the error (SSL-relate or otherwise).

**Comment by jbg** [comment]
Yep, I get a stack trace:

```
java.lang.IllegalArgumentException: cipherSuite TLS_DHE_DSS_WITH_AES_128_CBC_SHA is not supported.
  at com.android.org.conscrypt.NativeCrypto.checkEnabledCipherSuites(NativeCrypto.java:1036)
  at com.android.org.conscrypt.SSLParametersImpl.setEnabledCipherSuites(SSLParametersImpl.java:283)
  at com.android.org.conscrypt.OpenSSLSocketImpl.setEnabledCipherSuites(OpenSSLSocketImpl.java:912)
  at at.univie.sensorium.extinterfaces.HTTPSUploader$MySSLSocketFactory.createSocket(HTTPSUploader.java:241)
  at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
  at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
  at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
  at at.univie.sensorium.extinterfaces.HTTPSUploader.uploadFiles(HTTPSUploader.java:123)
  at at.univie.sensorium.extinterfaces.HTTPSUploader.doInBackground(HTTPSUploader.java:87)
  at at.univie.sensorium.extinterfaces.HTTPSUploader.doInBackground(HTTPSUploader.java:73)
  at android.os.AsyncTask$2.call(AsyncTask.java:305)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)
```

I assume this has something to do with the manually-listed enabled ciphers in `HTTPSUploader`. The documentation for `setEnabledCipherSuites` says it will throw this `IllegalArgumentException` if any of the listed cipher suites are not actually supported by the TLS implementation on the device. I run a hardened Android so it’s possible that some cipher suites are disabled system-wide.

I realise that the intention of listing the ciphers manually is to remove support for insecure ciphers; however, manually listing ciphers can have the opposite effect, for example because there are other ciphers not on your list that are widely considered to have good security properties. By listing the ciphers manually, you bring upon yourself (/the project) the maintenance burden of keeping the list up-to-date.

I think an argument could be made that in the context of this app, if a user wanted to select ciphers manually, they could do that on the server side (since they almost certainly control it).

**Comment by jbg** [comment]
Can confirm that if I comment out the `setEnabledCipherSuites` call, the problem no longer occurs.
